[package]
name = "kirum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
regex = "1.7.0"
thiserror = "1.0.38"