name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  examples:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate Daughter
      run: cargo run -- generate daughter -d examples/generate_daughter -a "Old Exemplum" -n "Middle Exemplum" -e examples/generate_daughter/etymology/example_daughter_transform.json -o examples/generate_daughter/tree/middle_exemplum.json
    - name: Post-Generate Daughter render
      run: cargo run -- render -d examples/generate_daughter line

    - name: Bureaucracy
      run: cargo run -- render -d examples/bureaucracy line

    - name: Conditionals Generate
      run: cargo run -- generate daughter -d examples/conditionals -e examples/conditionals/etymology/example_daughter_transform.json -a "Old Exemplum" -n "Middle Exemplum" -o examples/conditionals/tree/middle.json

    - name: Conditionals render
      run: cargo run -- render -d examples/conditionals line
      
    - name: templates
      run: cargo run -- -o rendered.asciidoc render -d examples/templates template -t examples/templates/tmpl/lexicon.hbs -r examples/templates/tmpl/shorten_pos.rhai

    - name: Phonetic generation render
      run: cargo run -- render -d examples/phonetic_rules json

    - name: Ingest
      run: cargo run -- ingest -d examples/ingest_from_json/empty_language -o generate=word -o language="example" json examples/ingest_from_json/input.json
    - name: Post-ingest render 
      run: cargo run -- render -d examples/ingest_from_json/empty_language line

    - name: Globals
      run: cargo run -- render -d examples/global_transforms line