name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  examples:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate Daughter
      run: cargo run -- generate daughter -d examples/generate_daughter -a "Old Exemplum" -n "Middle Exemplum" -e examples/generate_daughter/etymology/example_daughter_transform.json -o examples/generate_daughter/tree/middle_exemplum.json
    - name: Post-Generate Daughter render
      run: cargo run -- render -d examples/generate_daughter line

    - name: Bureaucracy
      run: cargo run -- render -d examples/bureaucracy line

    - name: templates
      run: cargo run -- -o rendered.asciidoc render -d examples/templates template -t examples/templates/tmpl/lexicon.hbs -r examples/templates/tmpl/shorten_pos.rhai